LambdaTest Taiko-Gauge Sample
LambdaTest/lambdatest-taiko-sample pull request #2
Opened 2023-01-30 08:35 UTC by mukesh-lt

Build id 10808873

2023-01-30 08:36 UTC, asad9711 approved these changes

2023-01-30 08:38 UTC, ankur-lt requested changes
Will be releasing new version of plugin. We will add those changes into this PR too.

2023-01-30 09:09 UTC, ankur-lt requested changes

2023-01-30 09:09 UTC, ankur-lt commented on README.md
> +- Install taiko globally using `npm install -g taiko`
Just npm install will work as all these dependencies are already added in package.json

2023-01-30 09:09 UTC, ankur-lt commented on taiko-gauge/tests/step_implementation.js
> +    'browserName': 'Chrome',
Also include other caps given here: https://github.com/LambdaTest/playwright-sample/blob/2801895c85e754580816af0dace3c849cceedc99/playwright-single.js#L8-L21

2023-01-30 10:58 UTC, ankur-lt requested changes

2023-01-30 10:58 UTC, ankur-lt commented on README.md
> +- Install taiko globally using `npm install -g taiko`
This needs to be modified.

2023-01-31 08:41 UTC, ankur-lt approved these changes

2023-01-31 08:43 UTC, merged